### ISSUE TITLE
Canvas Resize Issue 

### ISSUE THREAD

**Issue by BeulahLand24** [BeulahLand24/Generative-Root-Growth#2]
When a user accesses and loads a page while using inspect mode, and then attempts to exit inspect, the HTML canvas becomes warped due to incorrect resizing to match the new window width and height. This is also true if the user chooses to inspect after the page has finished loading. An event listener should fix this issue
![Screenshot 2024-03-21 230914](https://github.com/BeulahLand24/Generative-Root-Growth/assets/163823539/6b5b29fe-3c7a-46f6-8834-30e5e3c22e23)

**Comment by sebe324** [comment]
Hello, I'd like to work on this issue.
